# This is a basic workflow to help you get started with Actions

name: docker_action:0.0

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string : weekly,Sunday,11:00 #m h d/m m d/w 
    - cron:  '00 12 * * 0'

jobs:
  docker-run-action:
    runs-on: ubuntu-latest
    container:
      image: tamboraorg/crecoding:2020.0
      env:
        NODE_ENV: development
      ports:
        - 80
      volumes:
        - ${{ github.workspace }}:/cre/R
    steps:
      - uses: actions/checkout@v3
      - name: Set ownership
        run: |
          # this is to fix GIT not liking owner of the checkout dir
          chown -R $(id -u):$(id -g) $PWD
#        with:
#          ref: master

##      - name: Install liblapack-dev gfortran
##        run: (apt-get -y --no-install-recommends install liblapack-dev gfortran) 

##      - name: Install RcppArmadillo
##        run: (R -e "install.packages('RcppArmadillo')")
##      - name: Install Lmoments
##        run: (R -e "install.packages('Lmoments')")
##      - name: Install lmomco
##        run: (R -e "install.packages('lmomco')")

      - name: Install qdapTools
        run: (R -e "install.packages('qdapTools')")
      - name: Run knitr 
        run: (R -e "rmarkdown::render('/cre/R/README.Rmd')")
      - name: Run knitr P/T
        run: (R -e "rmarkdown::render('/cre/R/PI_and_TI.Rmd')")
      - name: Run knitr P
        run: (R -e "rmarkdown::render('/cre/R/PI_only.Rmd')")
      - name: Submit changes       
        uses: EndBug/add-and-commit@v9
